export const biologyCards = [
  { id: "b1", subject: "Biology", topic: "The Living World", front: "Taxonomic Hierarchy", back: "Kingdom → Phylum/Division → Class → Order → Family → Genus → Species" },
  { id: "b2", subject: "Biology", topic: "Classification", front: "Five Kingdom System", back: "Monera, Protista, Fungi, Plantae, Animalia (by R.H. Whittaker, 1969)" },
  { id: "b3", subject: "Biology", topic: "Classification", front: "Monera cell wall", back: "Peptidoglycan (Non-cellulosic) - Polysaccharide + amino acid" },
  { id: "b4", subject: "Biology", topic: "Classification", front: "Diatomaceous Earth", back: "Accumulation of cell wall deposits of Diatoms (Chrysophytes)" },
  { id: "b5", subject: "Biology", topic: "Fungi", front: "Fungi cell wall", back: "Chitin and Polysaccharides" },
  { id: "b6", subject: "Biology", topic: "Plant Kingdom", front: "Amphibians of Plant Kingdom", back: "Bryophytes (Require water for sexual reproduction)" },
  { id: "b7", subject: "Biology", topic: "Plant Kingdom", front: "Double Fertilization", back: "Unique to Angiosperms: Syngamy (zygote) + Triple Fusion (endosperm)" },
  { id: "b8", subject: "Biology", topic: "Animal Kingdom", front: "Phylum Porifera", back: "Sponges: Cellular level, Asymmetrical, Choanocytes, Water transport system" },
  { id: "b9", subject: "Biology", topic: "Animal Kingdom", front: "Phylum Cnidaria", back: "Cnidoblasts, Radial symmetry, Polyp and Medusa forms" },
  { id: "b10", subject: "Biology", topic: "Animal Kingdom", front: "Phylum Platyhelminthes", back: "Flatworms: Acoelomate, Bilateral symmetry, Flame cells" },
  { id: "b11", subject: "Biology", topic: "Animal Kingdom", front: "Phylum Arthropoda", back: "Largest phylum: Jointed appendages, Chitinous exoskeleton, Malpighian tubules" },
  { id: "b12", subject: "Biology", topic: "Cell Biology", front: "Cell Theory", back: "Schleiden and Schwann. Omnis cellula-e cellula (Virchow)" },
  { id: "b13", subject: "Biology", topic: "Cell Biology", front: "Ribosomes", back: "70S in Prokaryotes, 80S in Eukaryotes. Non-membrane bound. Protein synthesis." },
  { id: "b14", subject: "Biology", topic: "Cell Biology", front: "Endomembrane System", back: "ER, Golgi, Lysosomes, Vacuoles" },
  { id: "b15", subject: "Biology", topic: "Cell Division", front: "Interphase phases", back: "G1 (growth), S (DNA replication), G2 (prep for mitosis)" },
  { id: "b16", subject: "Biology", topic: "Cell Division", front: "Meiosis I Prophase I", back: "Leptotene, Zygotene (synapsis), Pachytene (crossing over), Diplotene (chiasmata), Diakinesis" },
  { id: "b17", subject: "Biology", topic: "Biomolecules", front: "Zwitterion", back: "Amino acid containing both positive and negative charges" },
  { id: "b18", subject: "Biology", topic: "Biomolecules", front: "Enzyme lock & key", back: "Fischer. Induced fit hypothesis by Koshland." },
  { id: "b19", subject: "Biology", topic: "Plant Physio", front: "Water Potential (Ψw)", back: "Ψw = Ψs (solute potential) + Ψp (pressure potential)" },
  { id: "b20", subject: "Biology", topic: "Plant Physio", front: "Apoplast vs Symplast", back: "Apoplast = through cell walls (dead). Symplast = through living plasmodesmata" },
  { id: "b21", subject: "Biology", topic: "Photosynthesis", front: "Z-Scheme (Non-cyclic)", back: "PS II (P680) → ETC → PS I (P700) → NADP+. Generates ATP & NADPH." },
  { id: "b22", subject: "Biology", topic: "Photosynthesis", front: "RuBisCO", back: "Most abundant protein. Has both Carboxylase & Oxygenase activity." },
  { id: "b23", subject: "Biology", topic: "Photosynthesis", front: "C4 Pathway (Hatch Slack)", back: "Primary acceptor: PEP. First stable product: OAA (4C). Avoids photorespiration." },
  { id: "b24", subject: "Biology", topic: "Respiration", front: "Glycolysis", back: "Cytoplasm. Glucose → 2 Pyruvate. Net 2 ATP." },
  { id: "b25", subject: "Biology", topic: "Respiration", front: "Krebs Cycle", back: "Matrix of Mitochondria. Acetyl CoA + OAA → Citric Acid." },
  { id: "b26", subject: "Biology", topic: "Respiration", front: "Respiratory Quotient (RQ)", back: "Carbs = 1.0, Fats = ~0.7, Proteins = ~0.9" },
  { id: "b27", subject: "Biology", topic: "Plant Growth", front: "Auxin", back: "Apical dominance, root initiation, prevent early fruit drop." },
  { id: "b28", subject: "Biology", topic: "Plant Growth", front: "Gibberellins", back: "Internode elongation, seed germination (breaks dormancy)." },
  { id: "b29", subject: "Biology", topic: "Plant Growth", front: "Ethylene", back: "Gaseous hormone. Fruit ripening, senescence." },
  { id: "b30", subject: "Biology", topic: "Digestion", front: "Dental Formula (Human Adult)", back: "2123 / 2123 (Incisors, Canines, Premolars, Molars)" },
  { id: "b31", subject: "Biology", topic: "Digestion", front: "Gastric Gland Cells", back: "Mucus neck calls (mucus), Peptic/Chief (pepsinogen), Parietal/Oxyntic (HCl, Intrinsic factor)" },
  { id: "b32", subject: "Biology", topic: "Breathing", front: "Vital Capacity (VC)", back: "ERV + TV + IRV" },
  { id: "b33", subject: "Biology", topic: "Breathing", front: "Oxygen Dissociation Curve", back: "Sigmoid. Shifts Right = Low affinity (High pCO2, Low pH, High Temp)" },
  { id: "b34", subject: "Biology", topic: "Circulation", front: "Blood components", back: "Plasma (55%), Formed elements (45%: RBCs, WBCs, Platelets)" },
  { id: "b35", subject: "Biology", topic: "Circulation", front: "ECG Waves", back: "P wave: Atrial depolarization. QRS: Ventricular depolarization. T wave: Ventricular repolarization." },
  { id: "b36", subject: "Biology", topic: "Excretion", front: "Nephron Parts", back: "Bowman's Capsule, PCT, Loop of Henle, DCT" },
  { id: "b37", subject: "Biology", topic: "Excretion", front: "RAAS Mechanism", back: "Renin (JGA) converts Angiotensinogen → Ang I → Ang II (vasoconstrictor). Aldosterone reabsorbs Na+." },
  { id: "b38", subject: "Biology", topic: "Locomotion", front: "Muscle Contraction", back: "Sliding Filament Theory: Actin slides over Myosin. Calcium binds Troponin." },
  { id: "b39", subject: "Biology", topic: "Locomotion", front: "Human Bones (206)", back: "Axial (80) + Appendicular (126)" },
  { id: "b40", subject: "Biology", topic: "Neural Control", front: "Action Potential", back: "Depolarization (Na+ influx), Repolarization (K+ efflux)" },
  { id: "b41", subject: "Biology", topic: "Neural Control", front: "Ear Ossicles", back: "Malleus, Incus, Stapes (amplifies sound)" },
  { id: "b42", subject: "Biology", topic: "Endocrine", front: "Pituitary Gland", back: "Anterior: GH, PRL, TSH, ACTH, LH, FSH. Posterior: Oxytocin, ADH/Vasopressin" },
  { id: "b43", subject: "Biology", topic: "Endocrine", front: "Insulin & Glucagon", back: "Pancreas Islets. Alpha cells: Glucagon (Hyperglycemic). Beta cells: Insulin (Hypoglycemic)." },
  { id: "b44", subject: "Biology", topic: "Reproduction", front: "Male Access. Ducts", back: "Rete testis → Vasa efferentia → Epididymis → Vas deferens" },
  { id: "b45", subject: "Biology", topic: "Reproduction", front: "Menstrual Cycle", back: "Menstrual, Follicular (Proliferative), Luteal (Secretory). LH surge = Ovulation." },
  { id: "b46", subject: "Biology", topic: "Repro Health", front: "Contraceptives", back: "IUDs (Copper T), Oral pills (Progestogen), Barrier methods" },
  { id: "b47", subject: "Biology", topic: "Genetics", front: "Test Cross", back: "Crossing F1 dominant with homozygous recessive. Monohybrid ratio = 1:1" },
  { id: "b48", subject: "Biology", topic: "Genetics", front: "Codominance", back: "Both alleles expressed fully. Example: AB blood group" },
  { id: "b49", subject: "Biology", topic: "Genetics", front: "Sickle-cell Anemia", back: "Point mutation: Glutamic acid (GAG) to Valine (GUG) at 6th pos. of Beta globin." },
  { id: "b50", subject: "Biology", topic: "Genetics", front: "Aneuploidy Examples", back: "Down's Sync (Trisomy 21), Turner's (45, X0), Klinefelter's (47, XXY)" },
  { id: "b51", subject: "Biology", topic: "Molecular", front: "DNA Structure", back: "Watson-Crick Double Helix. A=T (2 H-bonds), G≡C (3 H-bonds)." },
  { id: "b52", subject: "Biology", topic: "Molecular", front: "Griffith Experiment", back: "Streptococcus pneumoniae. Transforming principle." },
  { id: "b53", subject: "Biology", topic: "Molecular", front: "Hershey-Chase Exp", back: "Bacteriophages (³²P DNA, ³⁵S Protein). Proved DNA is genetic material." },
  { id: "b54", subject: "Biology", topic: "Molecular", front: "Translation (Initiation code)", back: "AUG (Codes for Methionine)" },
  { id: "b55", subject: "Biology", topic: "Molecular", front: "Lac Operon", back: "Inducible operon. Lactose is inducer. Repressor binds operator." },
  { id: "b56", subject: "Biology", topic: "Evolution", front: "Homologous Organs", back: "Same structure, different function (Divergent evolution). Ex: Forelimbs of mammals." },
  { id: "b57", subject: "Biology", topic: "Evolution", front: "Analogous Organs", back: "Different structure, same function (Convergent evolution). Ex: Wings of bird and insect." },
  { id: "b58", subject: "Biology", topic: "Evolution", front: "Adaptive Radiation", back: "Evolution starting from a point and radiating. Ex: Darwin's Finches." },
  { id: "b59", subject: "Biology", topic: "Health & Disease", front: "Malaria Vector", back: "Female Anopheles mosquito. Pathogen: Plasmodium." },
  { id: "b60", subject: "Biology", topic: "Health & Disease", front: "Antibodies (Ig)", back: "IgA (Colostrum/secretions), IgG (Placenta cross), IgE (Allergy)" },
  { id: "b61", subject: "Biology", topic: "Health & Disease", front: "HIV/AIDS", back: "Retrovirus. Attacks Helper T-cells (CD4). ELISA test used." },
  { id: "b62", subject: "Biology", topic: "Biotechnology", front: "Restriction Endonucleases", back: "Molecular scissors. E.g., EcoRI cuts at GAATTC." },
  { id: "b63", subject: "Biology", topic: "Biotechnology", front: "PCR Steps", back: "Denaturation (94°C), Annealing (50-60°C), Extension (72°C - Taq pol)." },
  { id: "b64", subject: "Biology", topic: "Biotechnology", front: "Bt Cotton", back: "Bacillus thuringiensis. Cry genes produce insecticidal crystal proteins." },
  { id: "b65", subject: "Biology", topic: "Ecology", front: "Allen's Rule", back: "Mammals from colder climates have shorter ears and limbs to minimize heat loss." },
  { id: "b66", subject: "Biology", topic: "Ecology", front: "Gause's Principle", back: "Competitive Exclusion: Two closely related species competing for same resource cannot co-exist." },
  { id: "b67", subject: "Biology", topic: "Ecology", front: "Pyramid of Energy", back: "Always Upright. 10% law by Lindeman." },
  { id: "b68", subject: "Biology", topic: "Ecology", front: "Primary Succession", back: "Starts on bare rock. Pioneer species: Lichens." },
  { id: "b69", subject: "Biology", topic: "Biodiversity", front: "In situ vs Ex situ", back: "In situ (On site): National parks. Ex situ (Off site): Zoos, Seed banks." },
  { id: "b70", subject: "Biology", topic: "Environmental", front: "Biomagnification", back: "Increase in toxicant conc. at successive trophic levels (e.g. DDT)." }
];
