export const chemistryCards = [
  { id: "c1", subject: "Chemistry", topic: "Mole Concept", front: "Number of Moles", back: "n = Given Mass / Molar Mass" },
  { id: "c2", subject: "Chemistry", topic: "Mole Concept", front: "Moles for Gas at STP", back: "n = Vol at STP / 22.4 L" },
  { id: "c3", subject: "Chemistry", topic: "Mole Concept", front: "Molarity (M)", back: "M = Moles of Solute / Vol of Sol in L" },
  { id: "c4", subject: "Chemistry", topic: "Mole Concept", front: "Molality (m)", back: "m = Moles of Solute / Mass of Solvent in kg" },
  { id: "c5", subject: "Chemistry", topic: "Mole Concept", front: "Normality (N)", back: "N = Eq. Moles / Vol in L = Molarity × n-factor" },
  { id: "c6", subject: "Chemistry", topic: "Atomic Structure", front: "Energy of Photon", back: "E = hν = hc/λ" },
  { id: "c7", subject: "Chemistry", topic: "Atomic Structure", front: "Bohr Radius (Rn)", back: "R_n = 0.529 (n²/Z) Å" },
  { id: "c8", subject: "Chemistry", topic: "Atomic Structure", front: "Bohr Energy (En)", back: "E_n = -13.6 (Z²/n²) eV/atom" },
  { id: "c9", subject: "Chemistry", topic: "Atomic Structure", front: "Bohr Velocity (vn)", back: "v_n = 2.18 × 10⁶ (Z/n) m/s" },
  { id: "c10", subject: "Chemistry", topic: "Atomic Structure", front: "Rydberg Equation", back: "1/λ = R_H Z² [1/n₁² - 1/n₂²]" },
  { id: "c11", subject: "Chemistry", topic: "Atomic Structure", front: "de Broglie Wavelength", back: "λ = h / mv = h / √(2mK)" },
  { id: "c12", subject: "Chemistry", topic: "Atomic Structure", front: "Heisenberg's Uncertainty", back: "Δx · Δp ≥ h / 4π" },
  { id: "c13", subject: "Chemistry", topic: "Periodic Table", front: "Effective Nuclear Charge", back: "Z_eff = Z - σ (shielding constant)" },
  { id: "c14", subject: "Chemistry", topic: "Periodic Table", front: "Radius Trend", back: "Decreases across period, Increases down group" },
  { id: "c15", subject: "Chemistry", topic: "Periodic Table", front: "Ionization Energy Trend", back: "Increases across period, Decreases down group" },
  { id: "c16", subject: "Chemistry", topic: "Chemical Bonding", front: "Dipole Moment", back: "μ = q × d (Debye)" },
  { id: "c17", subject: "Chemistry", topic: "Chemical Bonding", front: "Formal Charge", back: "Valence e⁻ - NonBonding e⁻ - ½(Bonding e⁻)" },
  { id: "c18", subject: "Chemistry", topic: "Chemical Bonding", front: "Hybridization Form", back: "H = ½ (V + M - C + A)\nV=Valence, M=Monovalent, C=Cation, A=Anion" },
  { id: "c19", subject: "Chemistry", topic: "Gaseous State", front: "Ideal Gas Law", back: "PV = nRT" },
  { id: "c20", subject: "Chemistry", topic: "Gaseous State", front: "Density of Ideal Gas", back: "d = PM / RT" },
  { id: "c21", subject: "Chemistry", topic: "Gaseous State", front: "Dalton's Partial Pressure", back: "P_A = X_A P_total" },
  { id: "c22", subject: "Chemistry", topic: "Gaseous State", front: "Graham's Law of Diffusion", back: "r₁/r₂ = √(M₂/M₁)" },
  { id: "c23", subject: "Chemistry", topic: "Gaseous State", front: "Root Mean Square Vel.", back: "U_rms = √(3RT/M)" },
  { id: "c24", subject: "Chemistry", topic: "Gaseous State", front: "Average Velocity", back: "U_avg = √(8RT / πM)" },
  { id: "c25", subject: "Chemistry", topic: "Gaseous State", front: "Most Probable Velocity", back: "U_mp = √(2RT/M)" },
  { id: "c26", subject: "Chemistry", topic: "Gaseous State", front: "Van der Waals Eq", back: "(P + an²/V²)(V - nb) = nRT" },
  { id: "c27", subject: "Chemistry", topic: "Gaseous State", front: "Compressibility Factor", back: "Z = PV / nRT. For ideal, Z=1." },
  { id: "c28", subject: "Chemistry", topic: "Thermodynamics", front: "First Law", back: "ΔU = q + w (IUPAC: w = -PΔV)" },
  { id: "c29", subject: "Chemistry", topic: "Thermodynamics", front: "Enthalpy (H)", back: "H = U + PV\nΔH = ΔU + PΔV" },
  { id: "c30", subject: "Chemistry", topic: "Thermodynamics", front: "ΔH and ΔU Relation (Reaction)", back: "ΔH = ΔU + Δn_g RT" },
  { id: "c31", subject: "Chemistry", topic: "Thermodynamics", front: "Entropy change (Isothermal)", back: "ΔS = q_rev / T = nR ln(V₂/V₁)" },
  { id: "c32", subject: "Chemistry", topic: "Thermodynamics", front: "Gibbs Free Energy", back: "ΔG = ΔH - TΔS" },
  { id: "c33", subject: "Chemistry", topic: "Thermodynamics", front: "Spontaneity Criteria", back: "Spontaneous if ΔG < 0" },
  { id: "c34", subject: "Chemistry", topic: "Thermodynamics", front: "Standard Gibbs & K_eq", back: "ΔG° = -RT ln K_eq" },
  { id: "c35", subject: "Chemistry", topic: "Thermodynamics", front: "Kirchhoff's Eq", back: "ΔH_T2 - ΔH_T1 = ΔC_p (T₂ - T₁)" },
  { id: "c36", subject: "Chemistry", topic: "Chemical Equil", front: "Law of Mass Action (Keq)", back: "K_eq = [Products]^coeff / [Reactants]^coeff" },
  { id: "c37", subject: "Chemistry", topic: "Chemical Equil", front: "Kp and Kc Relation", back: "K_p = K_c (RT)^Δng" },
  { id: "c38", subject: "Chemistry", topic: "Chemical Equil", front: "Reaction Quotient (Q)", back: "If Q < K, shifts forward. If Q > K, shifts backward." },
  { id: "c39", subject: "Chemistry", topic: "Ionic Equil", front: "Ostwald's Dilution Law", back: "α = √(K_a / C) for weak acid" },
  { id: "c40", subject: "Chemistry", topic: "Ionic Equil", front: "Ionic Product of Water", back: "K_w = [H⁺][OH⁻] = 10⁻¹⁴ (at 298K)" },
  { id: "c41", subject: "Chemistry", topic: "Ionic Equil", front: "pH of Weak Acid", back: "pH = ½(pK_a - log C)" },
  { id: "c42", subject: "Chemistry", topic: "Ionic Equil", front: "Buffer (Acidic) pH", back: "pH = pK_a + log([Salt]/[Acid]) (Henderson Eq)" },
  { id: "c43", subject: "Chemistry", topic: "Ionic Equil", front: "Buffer (Basic) pOH", back: "pOH = pK_b + log([Salt]/[Base])" },
  { id: "c44", subject: "Chemistry", topic: "Ionic Equil", front: "Solubility Product (Ksp)", back: "For A_xB_y: K_sp = x^x y^y s^(x+y)" },
  { id: "c45", subject: "Chemistry", topic: "Redox", front: "Oxidation Number of O", back: "Usually -2. Peroxides -1. Superoxides -0.5. OF₂ is +2" },
  { id: "c46", subject: "Chemistry", topic: "Redox", front: "Equivalent Weight (Redox)", back: "E = Molar Mass / Change in O.N." },
  { id: "c47", subject: "Chemistry", topic: "Electrochemistry", front: "Cell Potential", back: "E_cell = E_cathode - E_anode (Red. Pots)" },
  { id: "c48", subject: "Chemistry", topic: "Electrochemistry", front: "Nernst Equation", back: "E = E° - (0.0591/n) log Q (at 298K)" },
  { id: "c49", subject: "Chemistry", topic: "Electrochemistry", front: "Faraday's 1st Law", back: "W = Z Q = (E/96500) I t" },
  { id: "c50", subject: "Chemistry", topic: "Electrochemistry", front: "Kohlrausch's Law", back: "Λ°_m = ν₊λ°₊ + ν₋λ°₋" },
  { id: "c51", subject: "Chemistry", topic: "Electrochemistry", front: "Degree of Dissociation", back: "α = Λ_m^c / Λ_m^∞" },
  { id: "c52", subject: "Chemistry", topic: "Chemical Kinetics", front: "Rate of Reaction", back: "R = ± d[C]/dt" },
  { id: "c53", subject: "Chemistry", topic: "Chemical Kinetics", front: "Zero Order Rate Eq", back: "[A] = [A]₀ - kt" },
  { id: "c54", subject: "Chemistry", topic: "Chemical Kinetics", front: "Zero Order Half-life", back: "t_½ = [A]₀ / 2k" },
  { id: "c55", subject: "Chemistry", topic: "Chemical Kinetics", front: "First Order Rate Eq", back: "k = (2.303/t) log([A]₀/[A])" },
  { id: "c56", subject: "Chemistry", topic: "Chemical Kinetics", front: "First Order Half-life", back: "t_½ = 0.693 / k" },
  { id: "c57", subject: "Chemistry", topic: "Chemical Kinetics", front: "Arrhenius Equation", back: "k = A e^(-Ea/RT)" },
  { id: "c58", subject: "Chemistry", topic: "Chemical Kinetics", front: "Arrhenius Log Form", back: "log(k₂/k₁) = (Ea/2.303R) [ (T₂-T₁)/(T₁T₂) ]" },
  { id: "c59", subject: "Chemistry", topic: "Surface Chemistry", front: "Freundlich Isotherm", back: "x/m = k P^(1/n)" },
  { id: "c60", subject: "Chemistry", topic: "Surface Chemistry", front: "Hardy-Schulze Rule", back: "Greater valency of flocculating ion = greater coagulating power." },
  { id: "c61", subject: "Chemistry", topic: "Solid State", front: "Density of Unit Cell", back: "d = (Z × M) / (N_A × a³)" },
  { id: "c62", subject: "Chemistry", topic: "Solid State", front: "Packing Efficiency (FCC)", back: "74%" },
  { id: "c63", subject: "Chemistry", topic: "Solid State", front: "Packing Efficiency (BCC)", back: "68%" },
  { id: "c64", subject: "Chemistry", topic: "Solid State", front: "Bragg's Equation", back: "nλ = 2d sinθ" },
  { id: "c65", subject: "Chemistry", topic: "Solid State", front: "Radius Ratio (Octahedral)", back: "0.414 ≤ r⁺/r⁻ < 0.732" },
  { id: "c66", subject: "Chemistry", topic: "Solutions", front: "Henry's Law", back: "P = K_H × X" },
  { id: "c67", subject: "Chemistry", topic: "Solutions", front: "Raoult's Law (Volatile)", back: "P_T = P_A° X_A + P_B° X_B" },
  { id: "c68", subject: "Chemistry", topic: "Solutions", front: "Relative Lowering of VP", back: "(P° - P_s)/P° = X_solute" },
  { id: "c69", subject: "Chemistry", topic: "Solutions", front: "Elevation in BP", back: "ΔT_b = i · K_b · m" },
  { id: "c70", subject: "Chemistry", topic: "Solutions", front: "Depression in FP", back: "ΔT_f = i · K_f · m" },
  { id: "c71", subject: "Chemistry", topic: "Solutions", front: "Osmotic Pressure", back: "π = iCRT" },
  { id: "c72", subject: "Chemistry", topic: "Solutions", front: "Van't Hoff Factor (i)", back: "i = Observed Property / Normal Property" },
  { id: "c73", subject: "Chemistry", topic: "Coordination", front: "Effective Atomic Number", back: "EAN = Z - Oxidation State + 2(Coord. Num)" },
  { id: "c74", subject: "Chemistry", topic: "Coordination", front: "Crystal Field Splitting", back: "Δ₀ = 10 Dq" },
  { id: "c75", subject: "Chemistry", topic: "Coordination", front: "Magnetic Moment (spin only)", back: "μ = √(n(n+2)) BM, where n = unpaired e⁻" },
  { id: "c76", subject: "Chemistry", topic: "Metallurgy", front: "Froth Floatation", back: "Used for Sulphide ores (ZnS, PbS)" },
  { id: "c77", subject: "Chemistry", topic: "Metallurgy", front: "Mond's Process", back: "Refining of Nickel using CO gas" },
  { id: "c78", subject: "Chemistry", topic: "Metallurgy", front: "Van Arkel Method", back: "Refining of Zr and Ti using Iodine" },
  { id: "c79", subject: "Chemistry", topic: "Organic Gen", front: "Markovnikov's Rule", back: "H adds to C with more H's; X adds to C with fewer H's" },
  { id: "c80", subject: "Chemistry", topic: "Organic Gen", front: "Zaitsev Rule", back: "Elimination yields the more highly substituted, more stable alkene" },
  { id: "c81", subject: "Chemistry", topic: "Organic Names", front: "Wurtz Reaction", back: "2R-X + 2Na (dry ether) → R-R + 2NaX" },
  { id: "c82", subject: "Chemistry", topic: "Organic Names", front: "Aldol Condensation", back: "Aldehydes/Ketones with α-H react in dil base to form β-hydroxy carbonyl" },
  { id: "c83", subject: "Chemistry", topic: "Organic Names", front: "Cannizzaro Reaction", back: "Aldehydes NO α-H react in conc base: disproportionate to acid + alcohol" },
  { id: "c84", subject: "Chemistry", topic: "Organic Names", front: "Friedel-Crafts Alkylation", back: "Benzene + RX (AlCl₃) → Alkyl Benzene" },
  { id: "c85", subject: "Chemistry", topic: "Organic Names", front: "Reimer-Tiemann", back: "Phenol + CHCl₃ + NaOH → Salicylaldehyde" },
  { id: "c86", subject: "Chemistry", topic: "Organic Names", front: "Kolbe's Reaction", back: "Phenol + CO₂ + NaOH → Salicylic Acid" },
  { id: "c87", subject: "Chemistry", topic: "Organic Names", front: "Rosenmund Reduction", back: "Acyl Chloride + H₂ (Pd/BaSO₄) → Aldehyde" },
  { id: "c88", subject: "Chemistry", topic: "Organic Names", front: "Clemmensen Reduction", back: "C=O + Zn(Hg)/HCl → CH₂ (Alkane)" },
  { id: "c89", subject: "Chemistry", topic: "Organic Names", front: "Wolf-Kishner Reduction", back: "C=O + NH₂NH₂/KOH → CH₂ (Alkane)" },
  { id: "c90", subject: "Chemistry", topic: "Organic Names", front: "Hoffmann Bromamide", back: "Amide + Br₂/KOH → Primary Amine (1 Carbon less)" },
  { id: "c91", subject: "Chemistry", topic: "Organic Names", front: "Gabriel Phthalimide", back: "Only prepares primary ALIPHATIC amines" },
  { id: "c92", subject: "Chemistry", topic: "Organic Names", front: "Sandmeyer Reaction", back: "Diazonium + CuCl/HCl → Chlorobenzene" },
  { id: "c93", subject: "Chemistry", topic: "Organic Names", front: "Gattermann Reaction", back: "Diazonium + Cu/HCl → Chlorobenzene" },
  { id: "c94", subject: "Chemistry", topic: "Organic Tests", front: "Tollens' Test", back: "AgNO₃ + NH₄OH. Aldehydes give Silver Mirror." },
  { id: "c95", subject: "Chemistry", topic: "Organic Tests", front: "Fehling's Test", back: "Aldehydes give red ppt of Cu₂O (except aromatic)" },
  { id: "c96", subject: "Chemistry", topic: "Organic Tests", front: "Iodoform Test", back: "Methyl ketones (or alcohols forming them) give yellow CHI₃ ppt with I₂/NaOH" },
  { id: "c97", subject: "Chemistry", topic: "Organic Tests", front: "Lucas Test", back: "ZnCl₂/HCl. Primary (no turb), Sec (5 mins), Tert (instant turbidity)" },
  { id: "c98", subject: "Chemistry", topic: "Organic Tests", front: "Hinsberg Test", back: "Benzenesulfonyl chloride differentiates 1°, 2°, 3° amines" },
  { id: "c99", subject: "Chemistry", topic: "Polymers", front: "Nylon 6,6 Monomers", back: "Adipic acid + Hexamethylene diamine" },
  { id: "c100", subject: "Chemistry", topic: "Polymers", front: "Terylene (Dacron) Monomers", back: "Ethylene glycol + Terephthalic acid" },
  { id: "c101", subject: "Chemistry", topic: "Polymers", front: "Bakelite Monomers", back: "Phenol + Formaldehyde" },
  { id: "c102", subject: "Chemistry", topic: "Polymers", front: "Neoprene Monomer", back: "Chloroprene (2-chloro-1,3-butadiene)" },
  { id: "c103", subject: "Chemistry", topic: "Biomolecules", front: "Glucose Structure", back: "Aldohexose; D-Glucose is dextrorotatory" },
  { id: "c104", subject: "Chemistry", topic: "Biomolecules", front: "Peptide Bond", back: "Amide linkage (-CO-NH-) between amino acids" },
  { id: "c105", subject: "Chemistry", topic: "Biomolecules", front: "Reducing Sugars", back: "All monosaccharides, maltose, lactose (Sucrose is NON-reducing)" },
  { id: "c106", subject: "Chemistry", topic: "Biomolecules", front: "DNA vs RNA bases", back: "DNA: A, T, G, C. RNA: A, U, G, C." },
  { id: "c107", subject: "Chemistry", topic: "Biomolecules", front: "Vitamin C", back: "Ascorbic acid; deficiency causes scurvy" },
  { id: "c108", subject: "Chemistry", topic: "Everyday Life", front: "Aspirin", back: "Acetylsalicylic acid (Analgesic & Antipyretic)" },
  { id: "c109", subject: "Chemistry", topic: "Everyday Life", front: "Paracetamol", back: "Analgesic and Antipyretic" },
  { id: "c110", subject: "Chemistry", topic: "Everyday Life", front: "Antacids", back: "Ranitidine, Cimetidine, Magnesium Hydroxide" },
  { id: "c111", subject: "Chemistry", topic: "p-Block", front: "Nitrous Oxide (N₂O)", back: "Laughing gas, neutral, linear structure" },
  { id: "c112", subject: "Chemistry", topic: "p-Block", front: "Contact Process", back: "Manufacture of H₂SO₄ (V₂O₅ catalyst)" },
  { id: "c113", subject: "Chemistry", topic: "p-Block", front: "Haber Process", back: "Manufacture of NH₃ (Fe catalyst, N₂ + 3H₂)" },
  { id: "c114", subject: "Chemistry", topic: "p-Block", front: "Ostwald Process", back: "Manufacture of HNO₃ from NH₃" },
  { id: "c115", subject: "Chemistry", topic: "p-Block", front: "Ozone Depletion", back: "Freons (CFCs) act as catalysts for O₃ breakdown" },
  { id: "c116", subject: "Chemistry", topic: "Periodic Table", front: "Most Electronegative", back: "Fluorine (F)" },
  { id: "c117", subject: "Chemistry", topic: "Periodic Table", front: "Highest Electron Affinity", back: "Chlorine (Cl) > F due to repulsion in small F atom" },
  { id: "c118", subject: "Chemistry", topic: "s-Block", front: "Plaster of Paris", back: "CaSO₄ · ½H₂O" },
  { id: "c119", subject: "Chemistry", topic: "s-Block", front: "Gypsum", back: "CaSO₄ · 2H₂O" },
  { id: "c120", subject: "Chemistry", topic: "s-Block", front: "Washing Soda", back: "Na₂CO₃ · 10H₂O" },
  { id: "c121", subject: "Chemistry", topic: "s-Block", front: "Baking Soda", back: "NaHCO₃" },
  { id: "c122", subject: "Chemistry", topic: "Isomerism", front: "Chiral Carbon", back: "Carbon attached to 4 different groups (stereocenter)" },
  { id: "c123", subject: "Chemistry", topic: "Isomerism", front: "Metamerism", back: "Different alkyl chains on either side of polyvalent functional group (e.g. Ethers)" },
  { id: "c124", subject: "Chemistry", topic: "Isomerism", front: "Tautomerism", back: "Dynamic equilibrium between structural isomers (Keto-Enol)" },
  { id: "c125", subject: "Chemistry", topic: "Surface Chemistry", front: "Tyndall Effect", back: "Scattering of light by colloidal particles" }
];
