export const mathCards = [
  { id: "m1", subject: "Mathematics", topic: "Sets", front: "De Morgan's Laws", back: "(A ∪ B)' = A' ∩ B'\n(A ∩ B)' = A' ∪ B'" },
  { id: "m2", subject: "Mathematics", topic: "Sets", front: "n(A ∪ B)", back: "n(A) + n(B) - n(A ∩ B)" },
  { id: "m3", subject: "Mathematics", topic: "Relations", front: "Equivalence Relation", back: "Must be Reflexive, Symmetric, and Transitive" },
  { id: "m4", subject: "Mathematics", topic: "Functions", front: "One-One (Injective)", back: "If f(x₁) = f(x₂), then x₁ = x₂" },
  { id: "m5", subject: "Mathematics", topic: "Functions", front: "Onto (Surjective)", back: "Range = Codomain" },
  { id: "m6", subject: "Mathematics", topic: "Trigonometry", front: "sin(A+B)", back: "sinA cosB + cosA sinB" },
  { id: "m7", subject: "Mathematics", topic: "Trigonometry", front: "cos(A+B)", back: "cosA cosB - sinA sinB" },
  { id: "m8", subject: "Mathematics", topic: "Trigonometry", front: "tan(A+B)", back: "(tanA + tanB) / (1 - tanA tanB)" },
  { id: "m9", subject: "Mathematics", topic: "Trigonometry", front: "sin(2A)", back: "2sinAcosA = 2tanA / (1 + tan²A)" },
  { id: "m10", subject: "Mathematics", topic: "Trigonometry", front: "cos(2A)", back: "cos²A - sin²A = 2cos²A - 1 = 1 - 2sin²A = (1-tan²A)/(1+tan²A)" },
  { id: "m11", subject: "Mathematics", topic: "Trigonometry", front: "sinC + sinD", back: "2 sin((C+D)/2) cos((C-D)/2)" },
  { id: "m12", subject: "Mathematics", topic: "Trigonometry", front: "cosC + cosD", back: "2 cos((C+D)/2) cos((C-D)/2)" },
  { id: "m13", subject: "Mathematics", topic: "Trigonometry", front: "cosC - cosD", back: "-2 sin((C+D)/2) sin((C-D)/2)" },
  { id: "m14", subject: "Mathematics", topic: "Trigonometry", front: "Sine Rule", back: "a/sinA = b/sinB = c/sinC = 2R" },
  { id: "m15", subject: "Mathematics", topic: "Trigonometry", front: "Cosine Rule (cosA)", back: "cosA = (b² + c² - a²) / 2bc" },
  { id: "m16", subject: "Mathematics", topic: "Inv Trig", front: "Domain of sin⁻¹(x)", back: "[-1, 1]" },
  { id: "m17", subject: "Mathematics", topic: "Inv Trig", front: "Range of sin⁻¹(x)", back: "[-π/2, π/2]" },
  { id: "m18", subject: "Mathematics", topic: "Inv Trig", front: "Range of cos⁻¹(x)", back: "[0, π]" },
  { id: "m19", subject: "Mathematics", topic: "Inv Trig", front: "tan⁻¹(x) + cot⁻¹(x)", back: "π/2 (for all x in R)" },
  { id: "m20", subject: "Mathematics", topic: "Inv Trig", front: "tan⁻¹(x) + tan⁻¹(y)", back: "tan⁻¹[(x+y)/(1-xy)] if xy < 1" },
  { id: "m21", subject: "Mathematics", topic: "Complex Num", front: "i²", back: "-1" },
  { id: "m22", subject: "Mathematics", topic: "Complex Num", front: "Modulus |z|", back: "√(a² + b²) for z = a + ib" },
  { id: "m23", subject: "Mathematics", topic: "Complex Num", front: "Argument arg(z)", back: "tan⁻¹(|b/a|), adjusting for quadrant" },
  { id: "m24", subject: "Mathematics", topic: "Complex Num", front: "Euler Form", back: "z = r e^(iθ) = r(cosθ + i sinθ)" },
  { id: "m25", subject: "Mathematics", topic: "Complex Num", front: "Cube Roots of Unity", back: "1, ω, ω² (where 1 + ω + ω² = 0, ω³ = 1)" },
  { id: "m26", subject: "Mathematics", topic: "Complex Num", front: "De Moivre's Theorem", back: "(cosθ + i sinθ)ⁿ = cos(nθ) + i sin(nθ)" },
  { id: "m27", subject: "Mathematics", topic: "Quadratic", front: "Location of Roots: Both > k", back: "D≥0, af(k)>0, -b/(2a) > k" },
  { id: "m28", subject: "Mathematics", topic: "P & C", front: "Permutation (ⁿPᵣ)", back: "n! / (n-r)!" },
  { id: "m29", subject: "Mathematics", topic: "P & C", front: "Combination (ⁿCᵣ)", back: "n! / [r!(n-r)!]" },
  { id: "m30", subject: "Mathematics", topic: "P & C", front: "Circular Permutation", back: "(n-1)! for distinct seating. (n-1)!/2 for necklace." },
  { id: "m31", subject: "Mathematics", topic: "P & C", front: "Derangements (Dₙ)", back: "n! (1 - 1/1! + 1/2! - 1/3! ... (-1)ⁿ/n!)" },
  { id: "m32", subject: "Mathematics", topic: "Binomial", front: "Middle Term (n is even)", back: "T_(n/2 + 1)" },
  { id: "m33", subject: "Mathematics", topic: "Binomial", front: "Sum of Binomial Coeff", back: "ⁿC₀ + ⁿC₁ + ... + ⁿCₙ = 2ⁿ" },
  { id: "m34", subject: "Mathematics", topic: "Binomial", front: "Sum of Odd/Even Coeff", back: "2ⁿ⁻¹" },
  { id: "m35", subject: "Mathematics", topic: "Sequences", front: "AP nth term", back: "aₙ = a + (n-1)d" },
  { id: "m36", subject: "Mathematics", topic: "Sequences", front: "AP Sum (Sₙ)", back: "(n/2)[2a + (n-1)d] = (n/2)(a + l)" },
  { id: "m37", subject: "Mathematics", topic: "Sequences", front: "GP nth term", back: "aₙ = a rⁿ⁻¹" },
  { id: "m38", subject: "Mathematics", topic: "Sequences", front: "GP Sum (Sₙ)", back: "a(1 - rⁿ) / (1 - r) if r < 1" },
  { id: "m39", subject: "Mathematics", topic: "Sequences", front: "AGP Sum to Infinity", back: "S_∞ = a/(1-r) + dr/(1-r)²" },
  { id: "m40", subject: "Mathematics", topic: "Sequences", front: "AM ≥ GM ≥ HM", back: "(a+b)/2 ≥ √ab ≥ 2ab/(a+b)" },
  { id: "m41", subject: "Mathematics", topic: "Sequences", front: "Sum of first n naturals", back: "Σn = n(n+1)/2" },
  { id: "m42", subject: "Mathematics", topic: "Sequences", front: "Sum of squares Σn²", back: "n(n+1)(2n+1) / 6" },
  { id: "m43", subject: "Mathematics", topic: "Sequences", front: "Sum of cubes Σn³", back: "[n(n+1)/2]²" },
  { id: "m44", subject: "Mathematics", topic: "Straight Lines", front: "Slope Formula", back: "m = (y₂ - y₁) / (x₂ - x₁)" },
  { id: "m45", subject: "Mathematics", topic: "Straight Lines", front: "Point-Slope Form", back: "y - y₁ = m(x - x₁)" },
  { id: "m46", subject: "Mathematics", topic: "Straight Lines", front: "Intercept Form", back: "x/a + y/b = 1" },
  { id: "m47", subject: "Mathematics", topic: "Straight Lines", front: "Normal Form", back: "x cosα + y sinα = p" },
  { id: "m48", subject: "Mathematics", topic: "Straight Lines", front: "Distance from Point to Line", back: "d = |Ax₁ + By₁ + C| / √(A² + B²)" },
  { id: "m49", subject: "Mathematics", topic: "Straight Lines", front: "Angle Between Two Lines", back: "tanθ = |(m₁ - m₂) / (1 + m₁m₂)|" },
  { id: "m50", subject: "Mathematics", topic: "Circles", front: "General Equation", back: "x² + y² + 2gx + 2fy + c = 0\nCenter: (-g, -f)\nRadius: √(g² + f² - c)" },
  { id: "m51", subject: "Mathematics", topic: "Circles", front: "Length of Tangent", back: "L = √(S₁)" },
  { id: "m52", subject: "Mathematics", topic: "Circles", front: "Eq of Tangent at (x₁,y₁)", back: "T = 0 (replace x²→xx₁, y²→yy₁, 2x→x+x₁)" },
  { id: "m53", subject: "Mathematics", topic: "Circles", front: "Orthogonal Circles Cond", back: "2g₁g₂ + 2f₁f₂ = c₁ + c₂" },
  { id: "m54", subject: "Mathematics", topic: "Parabola", front: "Standard Eq (y²=4ax)", back: "Focus: (a, 0)\nDirectrix: x = -a\nLatus Rectum: 4a" },
  { id: "m55", subject: "Mathematics", topic: "Parabola", front: "Parametric Point", back: "(at², 2at)" },
  { id: "m56", subject: "Mathematics", topic: "Parabola", front: "Tangent Eq (Slope Form)", back: "y = mx + a/m" },
  { id: "m57", subject: "Mathematics", topic: "Ellipse", front: "Standard Eq (x²/a² + y²/b² = 1)", back: "Eccentricity: e = √(1 - b²/a²)\nFoci: (±ae, 0)\nLR = 2b²/a" },
  { id: "m58", subject: "Mathematics", topic: "Ellipse", front: "Parametric Point", back: "(a cosθ, b sinθ)" },
  { id: "m59", subject: "Mathematics", topic: "Hyperbola", front: "Standard Eq", back: "x²/a² - y²/b² = 1\ne = √(1 + b²/a²)" },
  { id: "m60", subject: "Mathematics", topic: "Hyperbola", front: "Asymptotes", back: "y = ± (b/a)x" },
  { id: "m61", subject: "Mathematics", topic: "Hyperbola", front: "Rectangular Hyperbola", back: "xy = c². Parametric: (ct, c/t)" },
  { id: "m62", subject: "Mathematics", topic: "Limits", front: "Standard Limit: sinx/x", back: "lim(x→0) (sin x)/x = 1" },
  { id: "m63", subject: "Mathematics", topic: "Limits", front: "Standard Limit: e^x", back: "lim(x→0) (e^x - 1)/x = 1" },
  { id: "m64", subject: "Mathematics", topic: "Limits", front: "Form 1^∞", back: "lim f(x)^g(x) = e^[lim g(x)(f(x)-1)]" },
  { id: "m65", subject: "Mathematics", topic: "Derivatives", front: "d/dx (xⁿ)", back: "n xⁿ⁻¹" },
  { id: "m66", subject: "Mathematics", topic: "Derivatives", front: "d/dx (a^x)", back: "a^x ln(a)" },
  { id: "m67", subject: "Mathematics", topic: "Derivatives", front: "Product Rule", back: "u'v + uv'" },
  { id: "m68", subject: "Mathematics", topic: "Derivatives", front: "Quotient Rule", back: "(u'v - uv') / v²" },
  { id: "m69", subject: "Mathematics", topic: "Derivatives", front: "Chain Rule", back: "dy/dx = (dy/du) × (du/dx)" },
  { id: "m70", subject: "Mathematics", topic: "AOD", front: "Monotonicity", back: "f'(x) > 0 for strictly increasing\nf'(x) < 0 for strictly decreasing" },
  { id: "m71", subject: "Mathematics", topic: "AOD", front: "Maxima/Minima Condition", back: "f'(x) = 0.\nf''(x) > 0 (Local Min)\nf''(x) < 0 (Local Max)" },
  { id: "m72", subject: "Mathematics", topic: "AOD", front: "Eq of Tangent", back: "y - y₁ = f'(x₁)(x - x₁)" },
  { id: "m73", subject: "Mathematics", topic: "Integration", front: "∫ xⁿ dx", back: "xⁿ⁺¹ / (n+1) + C" },
  { id: "m74", subject: "Mathematics", topic: "Integration", front: "∫ 1/x dx", back: "ln|x| + C" },
  { id: "m75", subject: "Mathematics", topic: "Integration", front: "∫ e^x f(x) + e^x f'(x)", back: "e^x f(x) + C" },
  { id: "m76", subject: "Mathematics", topic: "Integration", front: "∫ dx/√(a²-x²)", back: "sin⁻¹(x/a) + C" },
  { id: "m77", subject: "Mathematics", topic: "Definite Int", front: "Property: ∫₀ᵃ f(x) dx", back: "∫₀ᵃ f(a-x) dx" },
  { id: "m78", subject: "Mathematics", topic: "Definite Int", front: "Property: Even/Odd [-a, a]", back: "If odd: 0\nIf even: 2∫₀ᵃ f(x) dx" },
  { id: "m79", subject: "Mathematics", topic: "Area", front: "Area under curve", back: "A = ∫|f(x)| dx" },
  { id: "m80", subject: "Mathematics", topic: "Diff Eq", front: "Order and Degree", back: "Order: Highest derivative.\nDegree: Power of highest derivative in polynomial form." },
  { id: "m81", subject: "Mathematics", topic: "Diff Eq", front: "Linear Eq Integrating Factor", back: "dy/dx + Py=Q, IF = e^∫P dx" },
  { id: "m82", subject: "Mathematics", topic: "Vectors", front: "Dot Product", back: "a·b = |a||b| cosθ" },
  { id: "m83", subject: "Mathematics", topic: "Vectors", front: "Projection of a on b", back: "(a·b) / |b|" },
  { id: "m84", subject: "Mathematics", topic: "3D Geom", front: "Direction Cosines", back: "l²+m²+n² = 1" },
  { id: "m85", subject: "Mathematics", topic: "3D Geom", front: "Angle bet. line & plane", back: "sinθ = (b·n) / (|b||n|)" },
  { id: "m86", subject: "Mathematics", topic: "3D Geom", front: "Distance: Point to Plane", back: "d = |Ax₁ + By₁ + Cz₁ + D| / √(A²+B²+C²)" },
  { id: "m87", subject: "Mathematics", topic: "Probability", front: "Addition Theorem", back: "P(A∪B) = P(A) + P(B) - P(A∩B)" },
  { id: "m88", subject: "Mathematics", topic: "Probability", front: "Independent Events", back: "P(A∩B) = P(A) × P(B)" },
  { id: "m89", subject: "Mathematics", topic: "Probability", front: "Binomial Dist Mean & Var", back: "Mean = np\nVar = npq" },
  { id: "m90", subject: "Mathematics", topic: "Statistics", front: "Variance Formula", back: "σ² = (Σ(xᵢ - x̄)²)/n = (Σxᵢ²/n) - x̄²" },
  { id: "m91", subject: "Mathematics", topic: "Statistics", front: "Change of Scale (Var)", back: "Var(ax + b) = a² Var(x)" },
  { id: "m92", subject: "Mathematics", topic: "Matrices", front: "Determinant Properties", back: "|AB| = |A||B|\n|kA| = kⁿ|A| (n is order)\n|adj A| = |A|ⁿ⁻¹" },
  { id: "m93", subject: "Mathematics", topic: "Matrices", front: "Orthogonal Matrix", back: "A(A^T) = I. So |A| = ±1" },
  { id: "m94", subject: "Mathematics", topic: "Matrices", front: "Idempotent Matrix", back: "A² = A" },
  { id: "m95", subject: "Mathematics", topic: "Determinants", front: "Cramer's Rule", back: "x = D₁/D, y = D₂/D, z = D₃/D" }
];
