export const physicsCards = [
  { id: "p1", subject: "Physics", topic: "Kinematics", front: "1st Eq of Motion", back: "v = u + at" },
  { id: "p2", subject: "Physics", topic: "Kinematics", front: "2nd Eq of Motion", back: "s = ut + ½at²" },
  { id: "p3", subject: "Physics", topic: "Kinematics", front: "3rd Eq of Motion", back: "v² = u² + 2as" },
  { id: "p4", subject: "Physics", topic: "Kinematics", front: "Displacement in nth second", back: "S_n = u + (a/2)(2n - 1)" },
  { id: "p5", subject: "Physics", topic: "Projectiles", front: "Time of Flight", back: "T = (2u sinθ) / g" },
  { id: "p6", subject: "Physics", topic: "Projectiles", front: "Maximum Height", back: "H = (u² sin²θ) / 2g" },
  { id: "p7", subject: "Physics", topic: "Projectiles", front: "Horizontal Range", back: "R = (u² sin2θ) / g" },
  { id: "p8", subject: "Physics", topic: "Projectiles", front: "Equation of Trajectory", back: "y = x tanθ - (gx²)/(2u²cos²θ)" },
  { id: "p9", subject: "Physics", topic: "Relative Motion", front: "Relative Velocity V_AB", back: "V_AB = V_A - V_B" },
  { id: "p10", subject: "Physics", topic: "River Boat", front: "Shortest Path Time", back: "t = d / √(v_b² - v_r²)" },
  { id: "p11", subject: "Physics", topic: "River Boat", front: "Shortest Time", back: "t = d / v_b" },
  { id: "p12", subject: "Physics", topic: "Newton's Laws", front: "Momentum", back: "p = mv" },
  { id: "p13", subject: "Physics", topic: "Newton's Laws", front: "2nd Law", back: "F_net = dp/dt = ma" },
  { id: "p14", subject: "Physics", topic: "Newton's Laws", front: "Impulse", back: "J = ∫ F dt = Δp" },
  { id: "p15", subject: "Physics", topic: "Friction", front: "Static Friction Max", back: "f_s(max) = μ_s N" },
  { id: "p16", subject: "Physics", topic: "Friction", front: "Kinetic Friction", back: "f_k = μ_k N" },
  { id: "p17", subject: "Physics", topic: "Friction", front: "Angle of Repose", back: "tan α = μ_s" },
  { id: "p18", subject: "Physics", topic: "Circular Motion", front: "Angular Velocity", back: "ω = dθ/dt = v/r" },
  { id: "p19", subject: "Physics", topic: "Circular Motion", front: "Centripetal Accel.", back: "a_c = v²/r = ω²r" },
  { id: "p20", subject: "Physics", topic: "Circular Motion", front: "Centripetal Force", back: "F_c = mv²/r" },
  { id: "p21", subject: "Physics", topic: "Circular Motion", front: "Max Safe Speed (Flat)", back: "v_max = √(μ_s rg)" },
  { id: "p22", subject: "Physics", topic: "Circular Motion", front: "Banking Angle (Frictionless)", back: "tan θ = v² / (rg)" },
  { id: "p23", subject: "Physics", topic: "Work & Energy", front: "Work Definition", back: "W = ∫ F · dx" },
  { id: "p24", subject: "Physics", topic: "Work & Energy", front: "Kinetic Energy", back: "K = ½mv² = p² / (2m)" },
  { id: "p25", subject: "Physics", topic: "Work & Energy", front: "Work-Energy Theorem", back: "W_net = ΔK" },
  { id: "p26", subject: "Physics", topic: "Work & Energy", front: "Spring Potential Energy", back: "U = ½kx²" },
  { id: "p27", subject: "Physics", topic: "Work & Energy", front: "Conservative Force", back: "F = -dU/dx" },
  { id: "p28", subject: "Physics", topic: "Power", front: "Instantaneous Power", back: "P = dW/dt = F · v" },
  { id: "p29", subject: "Physics", topic: "Collisions", front: "Coefficient of Restitution", back: "e = (v₂ - v₁) / (u₁ - u₂)" },
  { id: "p30", subject: "Physics", topic: "Center of Mass", front: "COM Position", back: "R_cm = (Σ m_i r_i) / (Σ m_i)" },
  { id: "p31", subject: "Physics", topic: "Center of Mass", front: "Velocity of COM", back: "V_cm = (Σ m_i v_i) / (Σ m_i)" },
  { id: "p32", subject: "Physics", topic: "Rotational Motion", front: "Moment of Inertia", back: "I = Σ m_i r_i² = ∫ r² dm" },
  { id: "p33", subject: "Physics", topic: "Rotational Motion", front: "MOI of Solid Sphere", back: "I = (2/5)MR²" },
  { id: "p34", subject: "Physics", topic: "Rotational Motion", front: "MOI of Hollow Sphere", back: "I = (2/3)MR²" },
  { id: "p35", subject: "Physics", topic: "Rotational Motion", front: "MOI of Disc", back: "I = (1/2)MR²" },
  { id: "p36", subject: "Physics", topic: "Rotational Motion", front: "Parallel Axis Theorem", back: "I = I_cm + Md²" },
  { id: "p37", subject: "Physics", topic: "Rotational Motion", front: "Perpendicular Axis Thm", back: "I_z = I_x + I_y" },
  { id: "p38", subject: "Physics", topic: "Rotational Motion", front: "Torque", back: "τ = r × F = Iα" },
  { id: "p39", subject: "Physics", topic: "Rotational Motion", front: "Angular Momentum", back: "L = r × p = Iω" },
  { id: "p40", subject: "Physics", topic: "Rotational Motion", front: "Rotational KE", back: "K_rot = ½Iω²" },
  { id: "p41", subject: "Physics", topic: "Gravitation", front: "Newton's Law of Gravity", back: "F = G m₁m₂ / r²" },
  { id: "p42", subject: "Physics", topic: "Gravitation", front: "Acc. due to Gravity", back: "g = GM / R²" },
  { id: "p43", subject: "Physics", topic: "Gravitation", front: "Gravity at Height h", back: "g' = g (1 - 2h/R) [for h << R]" },
  { id: "p44", subject: "Physics", topic: "Gravitation", front: "Gravity at Depth d", back: "g' = g (1 - d/R)" },
  { id: "p45", subject: "Physics", topic: "Gravitation", front: "Gravitational Potential", back: "V = -GM/r" },
  { id: "p46", subject: "Physics", topic: "Gravitation", front: "Gravitational PE", back: "U = -GMm/r" },
  { id: "p47", subject: "Physics", topic: "Gravitation", front: "Escape Velocity", back: "v_e = √(2GM/R) = √(2gR)" },
  { id: "p48", subject: "Physics", topic: "Gravitation", front: "Orbital Velocity", back: "v_o = √(GM/r)" },
  { id: "p49", subject: "Physics", topic: "Gravitation", front: "Kepler's 3rd Law", back: "T² ∝ r³" },
  { id: "p50", subject: "Physics", topic: "Properties of Matter", front: "Hooke's Law", back: "Stress ∝ Strain (up to elastic limit)" },
  { id: "p51", subject: "Physics", topic: "Properties of Matter", front: "Young's Modulus", back: "Y = (F/A) / (ΔL/L)" },
  { id: "p52", subject: "Physics", topic: "Properties of Matter", front: "Energy stored in wire", back: "U = ½ × Stress × Strain × Volume" },
  { id: "p53", subject: "Physics", topic: "Fluid Mechanics", front: "Pressure at depth h", back: "P = P₀ + ρgh" },
  { id: "p54", subject: "Physics", topic: "Fluid Mechanics", front: "Equation of Continuity", back: "A₁v₁ = A₂v₂" },
  { id: "p55", subject: "Physics", topic: "Fluid Mechanics", front: "Bernoulli's Eq", back: "P + ½ρv² + ρgh = constant" },
  { id: "p56", subject: "Physics", topic: "Fluid Mechanics", front: "Velocity of Efflux", back: "v = √(2gh)" },
  { id: "p57", subject: "Physics", topic: "Fluid Mechanics", front: "Stokes' Law", back: "F = 6πηrv" },
  { id: "p58", subject: "Physics", topic: "Fluid Mechanics", front: "Terminal Velocity", back: "v_t = 2r²(ρ - σ)g / (9η)" },
  { id: "p59", subject: "Physics", topic: "Fluid Mechanics", front: "Surface Tension", back: "T = F/L" },
  { id: "p60", subject: "Physics", topic: "Fluid Mechanics", front: "Excess Pressure (Drop)", back: "ΔP = 2T/R" },
  { id: "p61", subject: "Physics", topic: "Fluid Mechanics", front: "Excess Pressure (Bubble)", back: "ΔP = 4T/R" },
  { id: "p62", subject: "Physics", topic: "Thermal Properties", front: "Linear Expansion", back: "ΔL = L₀ α ΔT" },
  { id: "p63", subject: "Physics", topic: "Thermal Properties", front: "Heat Capacity", back: "Q = mcΔT" },
  { id: "p64", subject: "Physics", topic: "Thermal Properties", front: "Latent Heat", back: "Q = mL" },
  { id: "p65", subject: "Physics", topic: "Thermal Properties", front: "Rate of Heat Flow", back: "dH/dt = kA(T₁ - T₂) / L" },
  { id: "p66", subject: "Physics", topic: "Thermal Properties", front: "Stefan's Law", back: "E = σ T⁴ (for black body)" },
  { id: "p67", subject: "Physics", topic: "Thermal Properties", front: "Newton's Cooling Law", back: "dT/dt = -k(T - T_s)" },
  { id: "p68", subject: "Physics", topic: "Thermal Properties", front: "Wien's Displ Law", back: "λ_max T = b" },
  { id: "p69", subject: "Physics", topic: "Thermodynamics", front: "1st Law of Thermo", back: "ΔQ = ΔU + ΔW" },
  { id: "p70", subject: "Physics", topic: "Thermodynamics", front: "Work in Isothermal", back: "W = nRT ln(V₂/V₁)" },
  { id: "p71", subject: "Physics", topic: "Thermodynamics", front: "Adiabatic Eq", back: "PV^γ = const, TV^(γ-1) = const" },
  { id: "p72", subject: "Physics", topic: "Thermodynamics", front: "Mayer's Formula", back: "C_p - C_v = R" },
  { id: "p73", subject: "Physics", topic: "Thermodynamics", front: "Carnot Efficiency", back: "η = 1 - T₂/T₁" },
  { id: "p74", subject: "Physics", topic: "Thermodynamics", front: "COP of Refrigerator", back: "β = T₂ / (T₁ - T₂)" },
  { id: "p75", subject: "Physics", topic: "Kinetic Theory", front: "Ideal Gas Eq", back: "PV = nRT = NkT" },
  { id: "p76", subject: "Physics", topic: "Kinetic Theory", front: "Pressure of Gas", back: "P = (1/3) ρ v_rms²" },
  { id: "p77", subject: "Physics", topic: "Kinetic Theory", front: "V_rms", back: "v_rms = √(3RT/M) = √(3kT/m)" },
  { id: "p78", subject: "Physics", topic: "Kinetic Theory", front: "Avg Kinetic Energy", back: "E = (3/2) kT (per molecule)" },
  { id: "p79", subject: "Physics", topic: "Kinetic Theory", front: "Degree of Freedom Energy", back: "U = (f/2) nRT" },
  { id: "p80", subject: "Physics", topic: "SHM", front: "Restoring Force", back: "F = -kx" },
  { id: "p81", subject: "Physics", topic: "SHM", front: "Displacement eq", back: "x = A sin(ωt + φ)" },
  { id: "p82", subject: "Physics", topic: "SHM", front: "Velocity in SHM", back: "v = ω √(A² - x²)" },
  { id: "p83", subject: "Physics", topic: "SHM", front: "Acceleration in SHM", back: "a = -ω²x" },
  { id: "p84", subject: "Physics", topic: "SHM", front: "Time Period (Spring)", back: "T = 2π √(m/k)" },
  { id: "p85", subject: "Physics", topic: "SHM", front: "Time Period (Pendulum)", back: "T = 2π √(l/g)" },
  { id: "p86", subject: "Physics", topic: "Waves", front: "Wave Eq", back: "y = A sin(kx - ωt)" },
  { id: "p87", subject: "Physics", topic: "Waves", front: "Wave Velocity", back: "v = fλ = ω/k" },
  { id: "p88", subject: "Physics", topic: "Waves", front: "Speed on String", back: "v = √(T/μ)" },
  { id: "p89", subject: "Physics", topic: "Waves", front: "Speed of Sound", back: "v = √(γP/ρ) = √(γRT/M)" },
  { id: "p90", subject: "Physics", topic: "Waves", front: "Beat Frequency", back: "f_beat = |f₁ - f₂|" },
  { id: "p91", subject: "Physics", topic: "Waves", front: "Doppler Effect", back: "f' = f [ (v ± v_o) / (v ∓ v_s) ]" },
  { id: "p92", subject: "Physics", topic: "Electrostatics", front: "Coulomb's Law", back: "F = (1/4πε₀) (q₁q₂/r²)" },
  { id: "p93", subject: "Physics", topic: "Electrostatics", front: "Electric Field (Point Q)", back: "E = kq/r²" },
  { id: "p94", subject: "Physics", topic: "Electrostatics", front: "Electric Flux (Gauss)", back: "Φ = ∮ E · dA = q_in / ε₀" },
  { id: "p95", subject: "Physics", topic: "Electrostatics", front: "E Field of infinite wire", back: "E = λ / (2πε₀r)" },
  { id: "p96", subject: "Physics", topic: "Electrostatics", front: "E Field of sheet", back: "E = σ / (2ε₀)" },
  { id: "p97", subject: "Physics", topic: "Electrostatics", front: "Electric Potential", back: "V = kq/r" },
  { id: "p98", subject: "Physics", topic: "Electrostatics", front: "E and V relation", back: "E = -dV/dr" },
  { id: "p99", subject: "Physics", topic: "Electrostatics", front: "Dipole Moment", back: "p = q × 2a" },
  { id: "p100", subject: "Physics", topic: "Electrostatics", front: "Torque on Dipole", back: "τ = p × E = pE sinθ" },
  { id: "p101", subject: "Physics", topic: "Capacitance", front: "Parallel Plate Cap", back: "C = ε₀A / d" },
  { id: "p102", subject: "Physics", topic: "Capacitance", front: "Energy inside Cap", back: "U = ½CV² = Q² / (2C)" },
  { id: "p103", subject: "Physics", topic: "Capacitance", front: "Capacitors in Series", back: "1/C_eq = 1/C₁ + 1/C₂ + ..." },
  { id: "p104", subject: "Physics", topic: "Current Electricity", front: "Ohm's Law", back: "V = IR" },
  { id: "p105", subject: "Physics", topic: "Current Electricity", front: "Drift Velocity", back: "v_d = I / (neA) = (eE/m)τ" },
  { id: "p106", subject: "Physics", topic: "Current Electricity", front: "Resistivity & Temp", back: "ρ = ρ₀[1 + α(T-T₀)]" },
  { id: "p107", subject: "Physics", topic: "Current Electricity", front: "Wheatstone Bridge", back: "R₁/R₂ = R₃/R₄ (Balanced)" },
  { id: "p108", subject: "Physics", topic: "Magnetism", front: "Lorentz Force", back: "F = q(E + v × B)" },
  { id: "p109", subject: "Physics", topic: "Magnetism", front: "Radius in B field", back: "r = mv / qB" },
  { id: "p110", subject: "Physics", topic: "Magnetism", front: "Biot-Savart Law", back: "dB = (μ₀/4π) (I dl × r) / r³" },
  { id: "p111", subject: "Physics", topic: "Magnetism", front: "B of Center of Loop", back: "B = μ₀I / (2R)" },
  { id: "p112", subject: "Physics", topic: "Magnetism", front: "Ampere's Law", back: "∮ B · dl = μ₀ I_in" },
  { id: "p113", subject: "Physics", topic: "Magnetism", front: "B inside Solenoid", back: "B = μ₀ n I" },
  { id: "p114", subject: "Physics", topic: "Magnetism", front: "Force on Wire", back: "F = I(l × B)" },
  { id: "p115", subject: "Physics", topic: "Magnetism", front: "Force bet. parallel wires", back: "F/L = (μ₀ I₁ I₂) / (2πd)" },
  { id: "p116", subject: "Physics", topic: "Electromagnetic Induction", front: "Faraday's Law", back: "ε = -dΦ/dt" },
  { id: "p117", subject: "Physics", topic: "Electromagnetic Induction", front: "Motional EMF", back: "ε = B l v" },
  { id: "p118", subject: "Physics", topic: "Electromagnetic Induction", front: "Self Inductance", back: "Φ = LI, ε = -L (dI/dt)" },
  { id: "p119", subject: "Physics", topic: "Electromagnetic Induction", front: "Energy in Inductor", back: "U = ½ L I²" },
  { id: "p120", subject: "Physics", topic: "Alternating Current", front: "RMS Current", back: "I_rms = I₀ / √2" },
  { id: "p121", subject: "Physics", topic: "Alternating Current", front: "Impedance LCR", back: "Z = √[R² + (X_L - X_C)²]" },
  { id: "p122", subject: "Physics", topic: "Alternating Current", front: "Resonance Freq", back: "f_r = 1 / (2π √(LC))" },
  { id: "p123", subject: "Physics", topic: "Ray Optics", front: "Mirror Formula", back: "1/f = 1/v + 1/u" },
  { id: "p124", subject: "Physics", topic: "Ray Optics", front: "Lens Maker's Eq", back: "1/f = (μ-1)(1/R₁ - 1/R₂)" },
  { id: "p125", subject: "Physics", topic: "Modern Physics", front: "Photoelectric Eq", back: "K_max = hf - P_work" }
];
